### ISSUE TITLE
Cannot read property 'document'

### ISSUE THREAD

**Issue by Romane-T** [KamiKillertO/vscode-colorize#35]
In seeking if any error messages coming up for the extension Auto Rename Tag (Jun Han) in the Console, have found that getting error messages for this extension instead.

There are error messages at start-up of Code which sometimes (but not always) mention errors in this extension. On creating a new document via File->Save a more extensive error listing of those errors at start show in the Console. Copy and paste of message follows. I have inserted a space between what is red and what is indented and black in the Console:

shell.ts:475 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at q.push (/home/romane/.vscode/extensions/kamikillerto.vscode-colorize-0.4.2/out/src/extension.js:313:33)
    at Queue._next (/home/romane/.vscode/extensions/kamikillerto.vscode-colorize-0.4.2/out/src/lib/queue.js:30:13)
    at Queue.push (/home/romane/.vscode/extensions/kamikillerto.vscode-colorize-0.4.2/out/src/lib/queue.js:21:18)
    at vscode_1.workspace.onDidSaveTextDocument.document (/home/romane/.vscode/extensions/kamikillerto.vscode-colorize-0.4.2/out/src/extension.js:312:11)
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:16423)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:20054)
    at t.$acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:307992)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:277319)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135077)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:135754)

e.onUnexpectedError @ shell.ts:475
(anonymous function) @ shell.ts:435
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

Am advising Jun Hun of this post, as normally when double-clicking a tag, both the opening and closing tags become hi-lighted (which am assuming is the function of colorize).  When this happens then Auto Rename Tag also works. When only the starting tag is hi-lighted on the double-click, then Auto Rename Tag fails. In these eyes, this would appear to demonstrate a correspondence between the two extensions - knowing, as one says this, that he could equally be way off target - all he has is theory :)

**Comment by KamiKillertO** [comment]
Hi

I've push a fix for this issue and I'll release a new version soon.
Let me know if the issue still occur after

**Comment by KamiKillertO** [comment]
I've release the `v0.5.0` with the fix ^^
