### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by luminarious** [KamiKillertO/vscode-colorize#42]
Not sure what's wrong here. Tried installing-removing but it didn't resolve the issue.

```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Cannot read property 'rgb' of undefined: TypeError: Cannot read property 'rgb' of undefined
    at Promise (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/lib/extractors/browser-extractor.js:767:96)
    at BrowsersColorExtractor.extractColors (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/lib/extractors/browser-extractor.js:761:16)
    at Promise.all.extractors.map.extractor (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/lib/extractors/color-extractor.js:21:71)
    at Array.map (native)
    at ColorExtractor.extract (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/lib/extractors/color-extractor.js:21:44)
    at Function.findColors (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/lib/color-util.js:46:42)
    at Promise.all.context.editor.document.getText.split.map.map.line (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/extension.js:217:43)
    at Array.map (native)
    at initDecorations (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/extension.js:217:10)
    at colorize (/Users/hardikovamees/.vscode/extensions/kamikillerto.vscode-colorize-0.5.1/out/src/extension.js:272:12)
```

**Comment by luminarious** [comment]
Turns out it was a firewall issue >_<

**Comment by luminarious** [comment]
It's strange. It worked once so I closed the issue, but then reopening the editor it glitched out again.

**Comment by KamiKillertO** [comment]
🤔 ok I'll need more informations :

- What types of files were open when you've launched vscode (css, sass, stylus...)
- Is it possible to have the files content?

**Comment by you06** [comment]
test if the match text is in  `COLORS` before get the rgb hex `COLORS[match[1]].rgb`

if the match text is not in  `COLORS`, just skip this match to avoid error

modify code [https://github.com/KamiKillertO/vscode-colorize/blob/develop/src/lib/extractors/browser-extractor.ts#L765-L770](https://github.com/KamiKillertO/vscode-colorize/blob/develop/src/lib/extractors/browser-extractor.ts#L765-L770)

```typescript
while ((match = text.match(REGEXP)) !== null) {
  position += match.index + 1;
  if (COLORS[match[1]]) {
    colors.push(new Color(match[1], position, 1, COLORS[match[1]].rgb));
  }
  text = text.slice(match.index + 1 + match[1].length);
  position += match[1].length;
}
```

will solve this issue?

**Comment by KamiKillertO** [comment]
Did you still have an issue?
