### ISSUE TITLE
Bad contrast for OCKLH colors

### ISSUE THREAD

**Issue by sangrepura** [KamiKillertO/vscode-colorize#936]
I saw that in #112 you fixed the contrast for HEX but OKLCH currently has  bad contrast for me:

<img width="388" alt="Screenshot 2024-12-12 at 12 23 57 AM" src="https://github.com/user-attachments/assets/88a81b0c-8010-4cc2-819a-1defac405de5" />

<img width="380" alt="Screenshot 2024-12-12 at 12 25 54 AM" src="https://github.com/user-attachments/assets/a029fe95-9297-4595-b111-f7f6b4af4c1a" />

**Comment by KamiKillertO** [comment]
Yeah, I know, I made a mistake when adding the OKLAB and OKLCH format 🤦.
I was trying to simplify the color extraction and forgot the text contrast. I'm going to fix this very soon

**Comment by KamiKillertO** [comment]
I've just released a new version with the fix 👍

**Comment by sangrepura** [comment]
Thanks @KamiKillertO!  However when I upgrade to v0.15.1 I get these errors. 
The plugin runs fine if I roll back to v0.15.0

```
2024-12-12 15:18:04.649 [error] TypeError: Could not parse oklch(23% 0 313deg); as a color. Missing a plugin?
    at hp (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:59151)
    at de (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:59332)
    at new n (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:106486)
    at Ut.LD [as colorFromRegexp] (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:109481)
    at Ut.extractColor (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40703)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40299
    at Array.map (<anonymous>)
    at wc.extractOneColor (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40290)
    at Nn.__extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:115211)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:115017
    at Array.map (<anonymous>)
    at Nn.extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:114989)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:112866
    at Array.map (<anonymous>)
    at au.extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:112857)
    at du.findVariablesDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:119089)
    at hR (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:3073)
    at hR.next (<anonymous>)
    at t (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:924)
    at mu._run (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:995)
    at mu.run (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:800)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:4238
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at dB.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:63223)
    at Dy.S (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
 ```

**Comment by KamiKillertO** [comment]
@sangrepura Should be fixed by now

**Comment by sangrepura** [comment]
Thank you so much! 
I really appreciate this amazing (and incredibly useful) plugin as well as all the effort and time you've committed to creating and maintaining it!  ♡

**Comment by Clarkkkk** [comment]
@KamiKillertO Could you please publish the latest version to open vsx as well? It is still `0.14.0` currently (https://open-vsx.org/extension/kamikillerto/vscode-colorize).

**Comment by KamiKillertO** [comment]
Thanks for reminding me, Ive totally forgot open vsx
