### ISSUE TITLE
TypeError: Could not parse oklch(23% 0 313deg); as a color. Missing a plugin?

### ISSUE THREAD

**Issue by sangrepura** [KamiKillertO/vscode-colorize#938]
Problem statement:

When I upgrade to v0.15.1 I get these errors. 
The plugin runs fine if I roll back to v0.15.0

```
2024-12-12 15:18:04.649 [error] TypeError: Could not parse oklch(23% 0 313deg); as a color. Missing a plugin?
    at hp (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:59151)
    at de (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:59332)
    at new n (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:106486)
    at Ut.LD [as colorFromRegexp] (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:109481)
    at Ut.extractColor (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40703)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40299
    at Array.map (<anonymous>)
    at wc.extractOneColor (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:40290)
    at Nn.__extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:115211)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:115017
    at Array.map (<anonymous>)
    at Nn.extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:114989)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:112866
    at Array.map (<anonymous>)
    at au.extractDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:112857)
    at du.findVariablesDeclarations (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:44:119089)
    at hR (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:3073)
    at hR.next (<anonymous>)
    at t (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:924)
    at mu._run (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:995)
    at mu.run (/Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:800)
    at /Users/user/.vscode-insiders/extensions/kamikillerto.vscode-colorize-0.15.1/client/out/extension.js:51:4238
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at dB.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:63223)
    at Dy.S (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
 ```

**Comment by sangrepura** [comment]
I started hacking around and was able to fix the issue.
 
I noticed that color.js is [using OKLab](https://github.com/color-js/color.js/blob/2e9dd5cc2362b8b81669247a4c71980d5e945b1f/src/spaces/oklch.js#L25) as the base color space for OKLCH.  So instead of asking colorjs.io to parse `oklch(23% 0 313deg)` I tried using the OKLAB colorspace as an intermediate color space and manually extracted the L, C, H values and then  converted them to OKLab coordinates before converting to sRGB:

No errors and the contrast is working.
```
2024-12-12 17:07:55.486 [info] ExtensionService#_doActivateExtension kamikillerto.vscode-colorize, startup: true, activationEvent: '*'
```

I can submit a PR if you'd like.

<img width="576" alt="Screenshot 2024-12-12 at 5 23 59 PM" src="https://github.com/user-attachments/assets/e7c06fbe-1553-47d5-91bb-a4d5382fa36c" />

**Comment by KamiKillertO** [comment]
@sangrepura can you try again?
The problem was that I was sending the `;` when parsing the color, and Colorjs does not support this. I've released a fixed version that sends correct value to Colorjs.

**Comment by j0534ng31** [comment]
> @sangrepura can you try again? ... I've released a fixed version that sends correct value to Colorjs.

It works for me, thank you!

**Comment by sangrepura** [comment]
Yes, it works perfectly! Thanks for the incredibly quick response! 🔥
